language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  #- "3.6-dev" # 3.6 development branch
  #- "3.7-dev" # 3.7 development branch
  #- "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
script:
  # TODO: use `tox-travis` to re-use build steps from `tox.ini`.
  - "python setup.py install"
  - "coverage run -m pytest -s -vv tests/"
  - "coverage report --fail-under=100"
